name: Download a file from S3

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: macos-latest
    env:
      working-directory: ./BoostClusteringMaB
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        pip3 install boto3 
    - name: Download from NCP
      env: 
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: python3 download.py --access_key="$ACCESS_KEY" --secret_key="$SECRET_KEY"
      working-directory: ./BoostClusteringMaB
    - uses: montudor/action-zip@v0.1.1
      with:
        args: unzip -qq Pods -d Pods
    - name: ls
      run: ls
      working-directory: ./BoostClusteringMaB
