name: Download a file from S3

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: pip3 install boto3 
    - name: Download from NCP
      env: 
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: python3 download.py --access_key="$ACCESS_KEY" --secret_key="$SECRET_KEY"
    - name: Copy Pods to ProjectDirectory
      run: mv Pods.zip ./BoostClusteringMaB
    - uses: montudor/action-zip@v0.1.1
      working-directory: ./BoostClusteringMaB
      with:
        args: unzip -qq Pods.zip -d Pods
    - name: ls
      run: ls
